FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:7.0
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
EXPOSE 80

WORKDIR /src

COPY ["src/Server/Pomodorium.Server.csproj", "src/Server/"]
RUN dotnet restore "src/Server/Pomodorium.Server.csproj"

COPY . .

WORKDIR "/src/src/Server"

RUN dotnet build -c $BUILD_CONFIGURATION

ENTRYPOINT ["dotnet", "run", "--no-build", "--no-launch-profile", "-c", "$BUILD_CONFIGURATION", "--"]
