apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomodorium
spec:
  #replicas: 2
  selector:
    matchLabels:
      app: pomodorium
  template:
    metadata:
      labels:
        app: pomodorium
    spec:
      containers:
      - name: pomodorium
        image: mardsystems/pomodorium
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5174
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: read_database
spec:
  #replicas: 2
  selector:
    matchLabels:
      app: read_database
  template:
    metadata:
      labels:
        app: read_database
    spec:
      containers:
      - name: read_database
        image: mongo:3.6
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: write_database
spec:
  #replicas: 2
  selector:
    matchLabels:
      app: write_database
  template:
    metadata:
      labels:
        app: write_database
    spec:
      containers:
      - name: write_database
        image: mongo:3.6
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
