# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  pomodoriumserver:
    image: pomodoriumserver
    build:
      context: .
      dockerfile: src/Server/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5174:5174
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
