# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  pomodoriumserver:
    image: pomodoriumserver
    build:
      context: .
      dockerfile: src/Server/Dockerfile
    ports:
      - 5174:5174
